stages:
  - pre
  - deploy

audit:
  stage: pre
  image: node:10-alpine
  script:
    - npm audit
  tags:
    - docker

deploy:
  only:
    - master
  script:
    - docker-compose up --build -d
  tags:
    - shell
